### ISSUE TITLE
Errors with decompiling any .amx

### ISSUE THREAD

**Issue by Chaprnks** [AmyrAhmady/DeAMX#1]
![tthysmr](https://user-images.githubusercontent.com/6340970/43359415-334cd2fc-9270-11e8-9a51-b415586aab65.png)

**Comment by AmyrAhmady** [comment]
Try with a .amx file which doesn't have  `anti-deamx`  and tell me the results.
Also, please send more information about your issue.
Thanks.

**Comment by Chaprnks** [comment]
It seems to be any .amx with either Anti-DeAMX, or complex y_hooking in the code. Might actually just be any code with YSI library included (I'll have to confirm that later).
