### ISSUE TITLE
lua: deamx.lua:274: attempt to index field '?' (a nil value)

### ISSUE THREAD

**Issue by kiribancik** [AmyrAhmady/DeAMX#10]
hello, I encountered errors when decompiling AMX, I tried to decrypt the mod and failed, however, everything works with small systems
lua: deamx.lua:274: attempt to index field '?' (a nil value)
stack traceback:
        deamx.lua:274: in function 'decompileBlock'
        deamx.lua:192: in function 'decompileBlock'
        deamx.lua:521: in main chunk
        [C]: ?
Alas, there is no PWN

**Comment by AmyrAhmady** [comment]
If the gamemode is using YSI it's not possible
